//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureVerifier.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_XAdESStructureVerifierTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_XAdESStructureVerifierTests() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureVerifier.Properties.Resources_XAdESStructureVerifierTests", typeof(Resources_XAdESStructureVerifierTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot;
        ///  xsi:noNamespaceSchemaLocation=&quot;EP.xsd&quot;&gt;
        ///  &lt;Prescription&gt;
        ///    &lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;
        ///      &lt;Version Value=&quot;EPS1.0&quot; /&gt;
        ///    &lt;/PrescriptionManagement&gt;
        ///    &lt;PrescriptionDocument id=&quot;PrescriptionDocument&quot;&gt;
        ///      &lt;!-- test for SigningCertificateSignatureXmlTests. --&gt;
        ///    &lt;/PrescriptionDocument&gt;
        ///    &lt;PrescriptionSign&gt;
        ///      &lt;xs:Signature xmlns:xs=&quot;http://www [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FoundRequiredTag {
            get {
                return ResourceManager.GetString("FoundRequiredTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot;
        ///  xsi:noNamespaceSchemaLocation=&quot;EP.xsd&quot;&gt;
        ///  &lt;Prescription&gt;
        ///    &lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;
        ///      &lt;Version Value=&quot;EPS1.0&quot; /&gt;
        ///    &lt;/PrescriptionManagement&gt;
        ///    &lt;PrescriptionDocument id=&quot;PrescriptionDocument&quot;&gt;
        ///      &lt;!-- test for SigningCertificateSignatureXmlTests. --&gt;
        ///    &lt;/PrescriptionDocument&gt;
        ///    &lt;PrescriptionSign&gt;
        ///      &lt;xs:Signature xmlns:xs=&quot;http://www [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundRequiredTagA {
            get {
                return ResourceManager.GetString("NotFoundRequiredTagA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot;
        ///  xsi:noNamespaceSchemaLocation=&quot;EP.xsd&quot;&gt;
        ///  &lt;Prescription&gt;
        ///    &lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;
        ///      &lt;Version Value=&quot;EPS1.0&quot; /&gt;
        ///    &lt;/PrescriptionManagement&gt;
        ///    &lt;PrescriptionDocument id=&quot;PrescriptionDocument&quot;&gt;
        ///      &lt;!-- test for SigningCertificateSignatureXmlTests. --&gt;
        ///    &lt;/PrescriptionDocument&gt;
        ///    &lt;PrescriptionSign&gt;
        ///      &lt;xs:Signature xmlns:xs=&quot;http://www [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundRequiredTagBES {
            get {
                return ResourceManager.GetString("NotFoundRequiredTagBES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot;
        ///  xsi:noNamespaceSchemaLocation=&quot;EP.xsd&quot;&gt;
        ///  &lt;Prescription&gt;
        ///    &lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;
        ///      &lt;Version Value=&quot;EPS1.0&quot; /&gt;
        ///    &lt;/PrescriptionManagement&gt;
        ///    &lt;PrescriptionDocument id=&quot;PrescriptionDocument&quot;&gt;
        ///      &lt;!-- test for SigningCertificateSignatureXmlTests. --&gt;
        ///    &lt;/PrescriptionDocument&gt;
        ///    &lt;PrescriptionSign&gt;
        ///      &lt;xs:Signature xmlns:xs=&quot;http://www [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundSignedPropertiesType {
            get {
                return ResourceManager.GetString("NotFoundSignedPropertiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot;
        ///  xsi:noNamespaceSchemaLocation=&quot;EP.xsd&quot;&gt;
        ///  &lt;Prescription&gt;
        ///    &lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;
        ///      &lt;Version Value=&quot;EPS1.0&quot; /&gt;
        ///    &lt;/PrescriptionManagement&gt;
        ///    &lt;PrescriptionDocument id=&quot;PrescriptionDocument&quot;&gt;
        ///      &lt;!-- test for SigningCertificateSignatureXmlTests. --&gt;
        ///    &lt;/PrescriptionDocument&gt;
        ///    &lt;PrescriptionSign&gt;
        ///      &lt;xs:Signature xmlns:xs=&quot;http://www [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UndefinedSigunatureId {
            get {
                return ResourceManager.GetString("UndefinedSigunatureId", resourceCulture);
            }
        }
    }
}
