//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureVerifier.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_XmlSchema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_XmlSchema() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureVerifier.Properties.Resources_XmlSchema", typeof(Resources_XmlSchema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;DispensingId Value=&quot;2b93bf48-5ce0-4a2b-b977-df30171ea5bb&quot; /&gt;&lt;/DispensingManagement&gt;
        ///	&lt;Dispensing id=&quot;Dispensing&quot;&gt;
        ///		&lt;ReferencePrescription&gt;
        ///			&lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;&lt;Version Value=&quot;EPS1.0&quot;/&gt;&lt;PrescriptionId Value=&quot;6de8a27e-bbd1-418e-8d73-a90 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlSchemaDispensingError {
            get {
                return ResourceManager.GetString("XmlSchemaDispensingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;EP.xsd&quot;&gt;
        ///	&lt;Prescription&gt;
        ///		&lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;
        ///			&lt;version Value=&quot;EPS1.0&quot;/&gt;
        ///		&lt;/PrescriptionManagement&gt;
        ///		&lt;PrescriptionDocument id=&quot;PrescriptionDocument&quot;&gt;U0oxCjEsMSw4MDAwMDEwLDk5LOaknOiovOeUqOeXhemZogoyLDg1Mi04MTU0LOmVt+W0juecjOmVt+W0juW4ggozLDAzLTM3NzUtMzExMSwwMy0zNzc1LTMxMTIs44Gd44Gu5LuW6YCj57Wh5YWI77yQ77yRCjQsMiwwMSzlhoX [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlSchemaPrescriptionError {
            get {
                return ResourceManager.GetString("XmlSchemaPrescriptionError", resourceCulture);
            }
        }
    }
}
