//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureVerifier.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ArchiveTimeStamp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ArchiveTimeStamp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureVerifier.Properties.Resources_ArchiveTimeStamp", typeof(Resources_ArchiveTimeStamp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Signature Id=&quot;Id&quot; xmlns=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;&lt;SignedInfo Id=&quot;Id-Si-3&quot;&gt;&lt;CanonicalizationMethod Algorithm=&quot;http://www.w3.org/TR/2001/REC-xml-c14n-20010315&quot; /&gt;&lt;SignatureMethod Algorithm=&quot;http://www.w3.org/2001/04/xmldsig-more#rsa-sha256&quot; /&gt;&lt;Reference Id=&quot;Id-Ref-2&quot; URI=&quot;#Id-Manifest-1&quot; Type=&quot;http://www.w3.org/2000/09/xmldsig#Manifest&quot;&gt;&lt;Transforms&gt;&lt;Transform Algorithm=&quot;http://www.w3.org/TR/2001/REC-xml-c14n-20010315&quot; /&gt;&lt;/Transforms&gt;&lt;DigestMethod Algorithm=&quot;h [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MultiATS {
            get {
                return ResourceManager.GetString("MultiATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Signature Id=&quot;Id&quot; xmlns=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;&lt;SignedInfo Id=&quot;Id-Si-3&quot;&gt;&lt;CanonicalizationMethod Algorithm=&quot;http://www.w3.org/TR/2001/REC-xml-c14n-20010315&quot; /&gt;&lt;SignatureMethod Algorithm=&quot;http://www.w3.org/2001/04/xmldsig-more#rsa-sha256&quot; /&gt;&lt;Reference Id=&quot;Id-Ref-2&quot; URI=&quot;#Id-Manifest-1&quot; Type=&quot;http://www.w3.org/2000/09/xmldsig#Manifest&quot;&gt;&lt;Transforms&gt;&lt;Transform Algorithm=&quot;http://www.w3.org/TR/2001/REC-xml-c14n-20010315&quot; /&gt;&lt;/Transforms&gt;&lt;DigestMethod Algorithm=&quot;h [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MultiATSBase64Error {
            get {
                return ResourceManager.GetString("MultiATSBase64Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;/DispensingManagement&gt;
        ///	&lt;Dispensing id=&quot;Dispensing&quot;&gt;
        ///		&lt;ReferencePrescription&gt;
        ///			&lt;PrescriptionManagement id=&quot;PrescriptionManagement&quot;&gt;&lt;Version Value=&quot;EPS1.0&quot;/&gt;&lt;PrescriptionId Value=&quot;1439e0c5-7c1d-4512-861d-263de48417bf&quot;/&gt;&lt;/PrescriptionManagement&gt;&lt;PrescriptionDocument id [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundATS {
            get {
                return ResourceManager.GetString("NotFoundATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;DispensingId Value=&quot;2b93bf48-5ce0-4a2b-b977-df30171ea5bb&quot; /&gt;&lt;/DispensingManagement&gt;
        ///&lt;DispensingSign&gt;&lt;xs:Signature xmlns:xs=&quot;http://www.w3.org/2000/09/xmldsig#&quot; Id=&quot;DispensingSign&quot;&gt;&lt;xs:SignedInfo Id=&quot;id3f33acb9-SignedInfo&quot;&gt;&lt;xs:CanonicalizationMethod Algorithm=&quot;http://www.w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundKeyInfo {
            get {
                return ResourceManager.GetString("NotFoundKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;DispensingId Value=&quot;2b93bf48-5ce0-4a2b-b977-df30171ea5bb&quot; /&gt;&lt;/DispensingManagement&gt;
        ///&lt;DispensingSign&gt;&lt;xs:Signature xmlns:xs=&quot;http://www.w3.org/2000/09/xmldsig#&quot; Id=&quot;DispensingSign&quot;&gt;&lt;xs:SignedInfo Id=&quot;id3f33acb9-SignedInfo&quot;&gt;&lt;xs:CanonicalizationMethod Algorithm=&quot;http://www.w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundObject {
            get {
                return ResourceManager.GetString("NotFoundObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;DispensingId Value=&quot;2b93bf48-5ce0-4a2b-b977-df30171ea5bb&quot; /&gt;&lt;/DispensingManagement&gt;
        ///&lt;DispensingSign&gt;&lt;xs:Signature xmlns:xs=&quot;http://www.w3.org/2000/09/xmldsig#&quot; Id=&quot;DispensingSign&quot;&gt;&lt;xs:SignedInfo Id=&quot;id3f33acb9-SignedInfo&quot;&gt;&lt;xs:CanonicalizationMethod Algorithm=&quot;http://www.w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundReference {
            get {
                return ResourceManager.GetString("NotFoundReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;DispensingId Value=&quot;2b93bf48-5ce0-4a2b-b977-df30171ea5bb&quot; /&gt;&lt;/DispensingManagement&gt;
        ///&lt;DispensingSign&gt;&lt;xs:Signature xmlns:xs=&quot;http://www.w3.org/2000/09/xmldsig#&quot; Id=&quot;DispensingSign&quot;&gt;&lt;xs:SignedInfo Id=&quot;id3f33acb9-SignedInfo&quot;&gt;&lt;xs:CanonicalizationMethod Algorithm=&quot;http://www.w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundSignatureValue {
            get {
                return ResourceManager.GetString("NotFoundSignatureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;DispensingId Value=&quot;2b93bf48-5ce0-4a2b-b977-df30171ea5bb&quot; /&gt;&lt;/DispensingManagement&gt;
        ///&lt;DispensingSign&gt;&lt;xs:Signature xmlns:xs=&quot;http://www.w3.org/2000/09/xmldsig#&quot; Id=&quot;DispensingSign&quot;&gt;&lt;xs:SignedInfo2 Id=&quot;id3f33acb9-SignedInfo&quot;&gt;&lt;xs:CanonicalizationMethod Algorithm=&quot;http://www. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundSignedInfo {
            get {
                return ResourceManager.GetString("NotFoundSignedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Document xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; id=&quot;Document&quot; xsi:noNamespaceSchemaLocation=&quot;ED.xsd&quot;&gt;
        ///	&lt;DispensingManagement id=&quot;DispensingManagement&quot;&gt;
        ///		&lt;Version Value=&quot;EPD1.0&quot;/&gt;
        ///	&lt;DispensingId Value=&quot;2b93bf48-5ce0-4a2b-b977-df30171ea5bb&quot; /&gt;&lt;/DispensingManagement&gt;
        ///&lt;DispensingSign&gt;&lt;xs:Signature xmlns:xs=&quot;http://www.w3.org/2000/09/xmldsig#&quot; Id=&quot;DispensingSign&quot;&gt;&lt;xs:SignedInfo Id=&quot;id3f33acb9-SignedInfo&quot;&gt;&lt;xs:CanonicalizationMethod Algorithm=&quot;http://www.w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundUnsignedSignatureProperties {
            get {
                return ResourceManager.GetString("NotFoundUnsignedSignatureProperties", resourceCulture);
            }
        }
    }
}
